### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by fkhjoy** [megadose/nqntnqnqmb#1]
I am getting this error. Please help or fix it
![image](https://user-images.githubusercontent.com/25137428/90893244-7696df80-e3e0-11ea-8491-ff7efb3e4270.png)

**Comment by megadose** [comment]
I've already had this problem it comes from the rate limit linkedin so try to change account/ip

**Comment by fkhjoy** [comment]
Did you mean "search limit"?

**Comment by megadose** [comment]
Yes after a while number of queries block searches

**Comment by fkhjoy** [comment]
Got it. Thank You
